version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - dependencies-

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Run tests
          command: npm test -- --coverage

      - run:
          name: Publish coverage
          command:
            if [[ "$CODECLIMATE_REPO_TOKEN" ]]; then ./node_modules/.bin/codeclimate-test-reporter < coverage/lcov.info; fi

      - run:
          name: Builds
          command: npm run build
